# Exercise: Python Numerics
* The exercises below are intended to give us more familiarity with Python numerics
* For guidance, use the notes, the Python __`help()`__ function, or the online documentation

## First things first–import the __`numpy`__ package

## Create a vector of ten zeros

In [2]:
import numpy as np

In [12]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a vector of size ten with nine zeros and a '1' in the fifth position

In [24]:
ones = np.zeros(10)
ones[4]=1
ones

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [25]:
tentofortynine=np.arange(10, 50, 1)
tentofortynine

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Reverse the previous vector

In [27]:
tentofortynine[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
x2 = np.random.randint(8, size=(3, 3))
x2

array([[4, 0, 4],
       [4, 5, 0],
       [0, 6, 6]])

## Find the indices of the non-zero elements of the following array:

In [16]:
v = [1, 2, 0, 0, 4, 0]

In [17]:
np.nonzero(v)

(array([0, 1, 4]),)

## Create a 5x5 identity matrix

In [28]:
m = np.eye(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Create a 3x3x3 array with random values

In [31]:
x2 = np.random.random((3, 3,3))
x2

array([[[0.74242904, 0.44099451, 0.99342894],
        [0.89577624, 0.29500753, 0.53904333],
        [0.25925641, 0.01685039, 0.91730969]],

       [[0.26550587, 0.29582077, 0.28251812],
        [0.9216349 , 0.06119347, 0.29475239],
        [0.96423636, 0.0205922 , 0.36094219]],

       [[0.5632804 , 0.89935287, 0.77922479],
        [0.65102508, 0.05248797, 0.18115627],
        [0.55931553, 0.49628991, 0.17138819]]])

## Find the minimum and maximum values generated in the previous step

In [32]:
x2.min(),x2.max()

(0.01685038872171929, 0.9934289415386931)

## Create a vector with 30 random values and find its mean

In [33]:
v = np.random.random(30)
v.mean()

0.5821630144424657

## Create a 5x5 2d array with 1's around the edges and 0's in the middle

In [34]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Try to predict the outcome of each of the following cells before running them.

In [35]:
0 * np.nan

nan

In [36]:
np.nan == np.nan

False

In [37]:
np.inf > np.nan

False

In [38]:
np.nan - np.nan

nan

In [39]:
0.3 == 3 * 0.1

False

In [40]:
np.array(0) // np.array(0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [41]:
np.array(0) // np.array(0.)

nan

In [42]:
np.array(0) / np.array(0)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [43]:
np.array(0) / np.array(0.)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

## Find the integer part of the following array using four different methods:

In [44]:
a = np.random.uniform(0, 10, 10)
print(a)

[5.40575001 3.19067986 9.23575253 7.98930595 1.79342521 3.489875
 0.37723947 6.14925165 3.06949519 5.0491942 ]


## Create a vector of 10 values from 0 to 1, both included

In [ ]:
np.array(-1,)

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

## Subtract the mean of each row of the following matrix

In [ ]:
m = np.random.rand(3, 3)
print(m)

## Add 1,000,000 numbers together using __`numpy`__ vectorized operations

## Create a 4x4 array of the first 16 powers of 3