## Import the __`numpy`__ package

In [2]:
import numpy as np

## Create a vector of ten zeros

In [3]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [4]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [5]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Reverse the previous vector

In [6]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
m = np.arange(0, 9).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [ ]:
v = [1, 2, 0, 0, 4, 0] # Given

In [ ]:
np.nonzero(v)

## Create a 5x5 identity matrix

In [ ]:
m = np.eye(5)
m

## Create a 3x3x3 array with random values

In [8]:
a = np.random.random((3, 3, 3))
a

array([[[0.37669588, 0.52486483, 0.13982448],
        [0.43269419, 0.18031858, 0.93597346],
        [0.37942952, 0.3223385 , 0.63408693]],

       [[0.33923893, 0.75557975, 0.72214096],
        [0.75366779, 0.52679319, 0.13131126],
        [0.30192932, 0.345179  , 0.1368641 ]],

       [[0.12240209, 0.47679425, 0.38324025],
        [0.81664938, 0.01326258, 0.62634689],
        [0.59624768, 0.23797235, 0.44748022]]])

## Find the minimum and maximum values generated in the previous step

In [ ]:
a.min(), a.max()

## Create a vector with 30 random values and find its mean

In [ ]:
v = np.random.random(30)
v.mean()

## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [ ]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

## Try to predict the output of each of the following cells before running them

In [ ]:
0 * np.nan

In [ ]:
np.nan == np.nan

In [ ]:
np.inf > np.nan

In [ ]:
np.nan - np.nan

In [ ]:
0.3 == 3 * 0.1

In [ ]:
np.array(0) // np.array(0)

In [ ]:
np.array(0) // np.array(0.)

In [ ]:
np.array(0) / np.array(0)

In [ ]:
np.array(0) / np.array(0.)

## Find the integer part of the following array using four different methods:

In [ ]:
a = np.random.uniform(0, 10, 10)
a

In [ ]:
a.astype(int)

In [ ]:
np.floor(a)

In [ ]:
np.ceil(a) - 1

In [ ]:
np.trunc(a)

## Create a vector of 10 values from 0 to 1, both included

In [ ]:
v = np.linspace(0, 1, 10)
v

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
v = np.linspace(0, 1, 12)[1:-1]
v

## Subtract the mean of each row of the following matrix

In [ ]:
m = np.random.rand(3, 3)
m

In [ ]:
m - m.mean(axis=1, keepdims=True)

## Add 1,000,000 numbers together using __`numpy`__ vectorized operations

In [ ]:
v = np.random.random(1_000_000)
np.sum(v)

## Create a 4x4 array of the first 16 powers of 3

In [ ]:
a = np.arange(16).reshape((4, 4))
3 ** a